package net.dutymod.fixerupper.core.config;

import java.io.InputStream;
import java.io.InputStreamReader;
import java.io.Reader;
import java.nio.charset.StandardCharsets;
import java.util.HashMap;
import java.util.Locale;
import java.util.Map;

/**
 * The per-option help text, read out of the language file.
 *
 * <h2>Why this exists</h2>
 *
 * <p>FixerUpper ships a description for every option -- a hundred and twenty-odd of them, under
 * {@code duty.option.<name>} in {@code en_us.json} -- and used them only for tooltips in the
 * settings screen. The generated {@code duty.properties} got a category word and two lines of
 * boilerplate instead, so seventy-four options sat in the file with nothing to say what any of them
 * did. The text was already written; it just never reached the file people actually read.
 *
 * <h2>Why the JSON is parsed by hand</h2>
 *
 * <p>This runs from a mixin config plugin, during class loading, before mods exist. That is the
 * same constraint {@link net.dutymod.framework.DutyConfig} is built around, and the same answer:
 * touching a JSON library here risks a classloading cycle for the sake of reading a flat map of
 * string to string. The file is generated by this project and its shape is known, so a small
 * scanner is both sufficient and one less thing that can fail early.
 *
 * <p>Failure is never fatal. A missing or unreadable file means options get the same comments they
 * had before, which is exactly where this started.
 */
final class OptionDescriptions {

    private static final String LANG = "assets/duty_fixerupper/lang/en_us.json";
    private static final String PREFIX = "duty.option.";

    private static Map<String, String> descriptions;

    private OptionDescriptions() {}

    /** {@return the description for an option name like {@code mixin.perf.dynamic_resources}} */
    static synchronized String get(String optionName) {
        if (descriptions == null) {
            descriptions = load();
        }
        return descriptions.get(optionName);
    }

    private static Map<String, String> load() {
        Map<String, String> out = new HashMap<>();
        try (InputStream in = OptionDescriptions.class.getClassLoader().getResourceAsStream(LANG)) {
            if (in == null) {
                return out;
            }
            try (Reader reader = new InputStreamReader(in, StandardCharsets.UTF_8)) {
                parse(reader, out);
            }
        } catch (Exception e) {
            // Deliberately silent beyond this: the logger may not be usable this early, and the
            // consequence is cosmetic.
            return out;
        }
        return out;
    }

    /**
     * Reads {@code "key": "value"} pairs, keeping only the option ones.
     *
     * <p>Handles the escapes the language file can actually contain -- {@code \"} and {@code \\},
     * plus {@code \n} which a few descriptions use for paragraph breaks. Anything else is passed
     * through, because a description is going into a comment either way.
     */
    private static void parse(Reader reader, Map<String, String> out) throws Exception {
        StringBuilder token = new StringBuilder();
        String key = null;
        boolean inString = false;
        boolean escaped = false;

        int read;
        while ((read = reader.read()) != -1) {
            char c = (char) read;

            if (escaped) {
                token.append(switch (c) {
                    case 'n' -> '\n';
                    case 't' -> ' ';
                    default -> c;
                });
                escaped = false;
                continue;
            }
            if (inString && c == '\\') {
                escaped = true;
                continue;
            }
            if (c == '"') {
                if (inString) {
                    // A complete string: the first is a key, the next its value.
                    if (key == null) {
                        key = token.toString();
                    } else {
                        if (key.startsWith(PREFIX)) {
                            String name = key.substring(PREFIX.length());
                            String value = token.toString().trim();
                            if (!value.isEmpty()) {
                                out.put(name, clean(value));
                            }
                        }
                        key = null;
                    }
                    token.setLength(0);
                }
                inString = !inString;
                continue;
            }
            if (inString) {
                token.append(c);
            }
        }
    }

    /**
     * {@return the description with its markdown emphasis removed}
     *
     * <p>The tooltips use {@code **bold**}, which renders in a screen and reads as noise in a
     * properties comment.
     */
    private static String clean(String text) {
        return text.replace("**", "").replace("\n", " ").replaceAll("\\s+", " ").trim();
    }

    /** {@return how many descriptions were found; for diagnostics} */
    static synchronized int count() {
        if (descriptions == null) {
            descriptions = load();
        }
        return descriptions.size();
    }

    static {
        // Touching Locale here so the class initialises the same way regardless of default locale;
        // the keys are ASCII and must not be case-folded by a Turkish default.
        Locale.ROOT.getLanguage();
    }
}
