package net.dutymod.memory.enums;

import net.dutymod.framework.DutyLog;
import org.objectweb.asm.Type;

import java.lang.reflect.Method;

/**
 * Runtime support called from the generated cache holders.
 *
 * <p>Everything here is invoked from bytecode rather than Java source, so the method names and
 * descriptors must stay in step with {@link CacheClassGenerator}.
 *
 * <p>Upstream Jasione uses a third-party reflection library to find the caller's classloader. Duty
 * uses {@link StackWalker} instead, which is in the JDK, needs no {@code --add-opens}, and drops a
 * dependency from the jar.
 */
@SuppressWarnings("unused") // called from generated bytecode
public final class EnumValuesAccessor {
    static final String INTERNAL_NAME = Type.getInternalName(EnumValuesAccessor.class);

    private static final StackWalker WALKER =
            StackWalker.getInstance(StackWalker.Option.RETAIN_CLASS_REFERENCE);

    private EnumValuesAccessor() {}

    /**
     * {@return the enum constants of {@code binaryName}, or {@code null} if unavailable}
     *
     * <p>{@code null} is a valid answer: the holder only reads {@code VALUES} when {@code IS_ENUM}
     * is true, and that is computed by {@link #isEnum} with the same failure handling.
     */
    public static Object[] values(String binaryName) {
        Class<?> type = resolve(binaryName);
        if (type == null || !type.isEnum()) {
            return null;
        }
        try {
            return type.getEnumConstants();
        } catch (NoClassDefFoundError e) {
            // Reachable when an enum references a class from a mod that is not installed; the
            // original values() call would have failed the same way at its own call site.
            return null;
        }
    }

    /** {@return whether {@code binaryName} is an enum whose constants are safe to cache} */
    public static boolean isEnum(String binaryName) {
        Class<?> type = resolve(binaryName);
        if (type == null || !type.isEnum()) {
            return false;
        }
        if (isDynamicallyExtensible(type)) {
            DutyLog.debug("Not caching " + binaryName + ": the enum is dynamically extensible.");
            return false;
        }
        return true;
    }

    /**
     * Reflective fallback for the rare class that looks like an enum at the bytecode level but is
     * not accessible from the generated holder.
     */
    public static Object[] invokeValuesSlow(String binaryName) {
        Class<?> type = resolve(binaryName);
        if (type == null) {
            return null;
        }
        try {
            Method method = type.getDeclaredMethod(AsmNames.VALUES);
            method.setAccessible(true);
            return (Object[]) method.invoke(null);
        } catch (ReflectiveOperationException | RuntimeException e) {
            DutyLog.error("Could not invoke " + binaryName + ".values() reflectively", e);
            return null;
        }
    }

    /**
     * {@return whether entries can be appended to this enum after it is loaded}
     *
     * <p>Caching the constants of an extensible enum would hand out a stale array once another mod
     * adds a constant. NeoForge implements enum extension by transforming the enum class itself
     * before it loads, so its own mechanism is safe here; this check covers the Forge-style
     * {@code IExtensibleEnum} interface that mods may still carry.
     */
    private static boolean isDynamicallyExtensible(Class<?> type) {
        for (Class<?> iface : type.getInterfaces()) {
            if ("net.minecraftforge.common.IExtensibleEnum".equals(iface.getName())) {
                return true;
            }
        }
        return false;
    }

    private static Class<?> resolve(String binaryName) {
        // The caller is the generated holder, which lives in the same classloader as the enum it
        // caches. Asking it directly avoids depending on the thread context classloader, which is
        // not reliably set during class loading.
        ClassLoader loader = WALKER.getCallerClass().getClassLoader();
        try {
            return Class.forName(binaryName, false, loader);
        } catch (ClassNotFoundException | LinkageError e) {
            return null;
        }
    }
}
