#!/usr/bin/env python3
"""Convert a Fabric accessWidener (Yarn names) into a NeoForge access transformer (Mojang names).

The companion to yarn2mojang.py. A Yarn-authored mod that reaches into Minecraft's internals
ships an .accesswidener; NeoForge wants an accesstransformer.cfg, and the two differ in syntax
*and* in the names they use. Both halves have to be right, and a wrong name here fails the same
quiet way a wrong mixin target does -- the build is clean and the game dies at load.

Unlike the source translator, this resolves members against their declaring class rather than
by unique identifier. An accessWidener line names its owner, so there is no ambiguity to duck:
if ChunkSection.blockStateContainer is wanted, the owner is right there and the exact Mojang
field name for that class can be looked up. Descriptors are remapped type by type for the same
reason -- an AT line carrying a Yarn descriptor matches nothing.

Mapping of concepts:

    accessible method Owner name desc  ->  public Owner name(desc)
    accessible field  Owner name desc  ->  public Owner name
    mutable    field  Owner name desc  ->  public-f Owner name     (-f strips final)
    accessible class  Owner            ->  public Owner
    extendable class  Owner            ->  public-f Owner

ONE RULE THIS CANNOT DO FOR YOU
------------------------------
Fabric's accessWidener widens a virtual method's overrides automatically. NeoForge's access
transformer does not. Widening a base method on its own therefore fails the Minecraft recompile
with "attempting to assign weaker access privileges", naming the subclass that still overrides
it more narrowly. Finding overrides needs the full class hierarchy, which is more machinery than
this deserves -- and the recompile names them exactly, so the loop is: generate, build, read the
error, add the overrides. Keep those in a companion .extra.cfg next to the generated file so
regenerating never eats them.

Usage:
    python tools/aw2at.py <mappings.tiny> <input.accesswidener> <output.cfg>
"""
import collections
import pathlib
import re
import sys


def load(tiny_path: pathlib.Path):
    """classes {yarn->mojang}, and per-owner members {(yarn_owner, yarn_name) -> mojang_name}."""
    classes: dict[str, str] = {}
    members: dict[tuple[str, str], str] = {}

    with tiny_path.open(encoding="utf-8", errors="replace") as handle:
        header = handle.readline().rstrip("\n").split("\t")
        namespaces = header[3:]
        mojang_col, yarn_col = namespaces.index("official"), namespaces.index("named")

        yarn_owner = None
        for line in handle:
            if line.startswith("\t\t"):
                continue
            parts = line.rstrip("\n").split("\t")
            if parts[0] == "c" and len(parts) > 1 + max(mojang_col, yarn_col):
                mojang, yarn = parts[1 + mojang_col], parts[1 + yarn_col]
                if yarn and mojang:
                    classes[yarn] = mojang
                yarn_owner = yarn or None
            elif yarn_owner and len(parts) > 3 and parts[0] == "" and parts[1] in ("m", "f"):
                names = parts[3:]
                if len(names) > max(mojang_col, yarn_col):
                    mojang, yarn = names[mojang_col], names[yarn_col]
                    if yarn and mojang:
                        members[(yarn_owner, yarn)] = mojang
    return classes, members


TYPE = re.compile(r"L([A-Za-z0-9_/$]+);")


def remap_desc(desc: str, classes: dict[str, str]) -> str:
    return TYPE.sub(lambda m: "L" + classes.get(m.group(1), m.group(1)) + ";", desc)


def remap_owner(owner: str, classes: dict[str, str]) -> str:
    """Owners may be inner classes; map the whole thing, else map the outer and keep the tail."""
    if owner in classes:
        return classes[owner]
    if "$" in owner:
        outer, _, inner = owner.partition("$")
        if outer in classes:
            return classes[outer] + "$" + inner
    return owner


def main() -> int:
    if len(sys.argv) < 4:
        print(__doc__)
        return 2
    tiny, src, dest = (pathlib.Path(p) for p in sys.argv[1:4])
    classes, members = load(tiny)

    out = [
        "# Generated by tools/aw2at.py from " + src.name,
        "# Do not edit by hand; edit the accessWidener and regenerate.",
        "",
    ]
    unresolved: list[str] = []
    counts = collections.Counter()

    for raw in src.read_text(encoding="utf-8", errors="replace").splitlines():
        line = raw.strip()
        if not line or line.startswith("#") or line.startswith("accessWidener"):
            if line.startswith("#"):
                out.append(line)
            continue
        parts = line.split()
        access, kind, owner = parts[0], parts[1], parts[2]
        mojang_owner = remap_owner(owner, classes).replace("/", ".")
        if mojang_owner == owner.replace("/", "."):
            unresolved.append(f"class not in mappings: {owner}")

        if kind == "class":
            out.append(("public-f " if access == "extendable" else "public ") + mojang_owner)
            counts["class"] += 1
        elif kind in ("method", "field"):
            name, desc = parts[3], parts[4] if len(parts) > 4 else ""
            mojang_name = members.get((owner, name))
            if mojang_name is None:
                # <init> is never renamed; anything else missing is worth shouting about.
                mojang_name = name
                if name != "<init>":
                    unresolved.append(f"{kind} not in mappings: {owner}.{name}")
            prefix = "public-f " if access == "mutable" else "public "
            if kind == "method":
                out.append(f"{prefix}{mojang_owner} {mojang_name}{remap_desc(desc, classes)}")
            else:
                out.append(f"{prefix}{mojang_owner} {mojang_name}")
            counts[kind] += 1

    dest.parent.mkdir(parents=True, exist_ok=True)
    dest.write_text("\n".join(out) + "\n", encoding="utf-8")

    print(f"wrote {dest}")
    print(f"  {counts['class']} class, {counts['method']} method, {counts['field']} field entries")
    if unresolved:
        print(f"  {len(unresolved)} unresolved -- these will not widen anything:")
        for u in sorted(set(unresolved)):
            print(f"    {u}")
        return 1
    print("  all names resolved")
    return 0


if __name__ == "__main__":
    sys.exit(main())
